"use client";

import type { Metadata } from "next";
import SideBar from "./(component)/sidebar";
import ProtectedRoute from "../(components)/ProtectedRoute";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProtectedRoute>
      <div className="flex md:flex-row flex-col">
        <SideBar />
        <div className="p-9 flex-1">{children}</div>
      </div>
    </ProtectedRoute>
  );
}
