import type { Metadata } from "next";
import SideBar from "./(component)/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

     <div className="flex md:flex-row flex-col" >
     <SideBar />
  <div className="p-8 flex-1">
      {children}
  </div>
     </div>
         
  );
}
