import type { Metadata } from "next";
import SideBar from "./(component)/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

     <div>
     <SideBar />
    {children}
     </div>
         
  );
}
